export const posts = [
	{
		id: 1,
		content: "Is YC still a status symbol? A lot of the startups I’ve seen from recent batches are gpt wrappers at best. They don’t seem to be fronting the cutting edge anymore",
		username: "avighnash",
		createdAt: "2024-02-29T00:29:04.000Z",
	},
	{
		id: 2,
		content: "yeah i’m a woman in stem",
		username: "paularambles",
		createdAt: "2024-03-01T20:10:04.000Z",
	},
	{
		id: 3,
		content: "Anyone who has not heard their Apple Silicon machine's fans has not performed a long ffmpeg conversion",
		username: "ChristianSelig",
		createdAt: "2024-02-28T19:22:21.000Z",
	},
	{
		id: 4,
		content: "will be kinda funny/poetic if after AI-generated blogspam content floods the web, a bunch of netscape navigators and internet explorers rally together in secret to share links to human-made content",
		username: "visakanv",
		createdAt: "2024-02-28T15:25:38.000Z",
	},
	{
		id: 5,
		content: "Meet my concept. I think Browse for Me could work beautifully on the Apple Watch. What do you think?",
		username: "iamnalimov",
		cover: "https://www.imagineonline.store/cdn/shop/files/Apple_Watch_Series_9_LTE_45mm_Midnight_Aluminium_Midnight_Sport_Loop_PDP_Image_Position-7__en-IN_c6a2f263-d86b-40d0-8c76-53f393cae401.jpg?v=1698865803&width=380",
		createdAt: "2024-02-28T18:53:08.000Z",
	},
	{
		id: 6,
		content: "i like collecting pokemon\n\n(friends that I can see on Find My)",
		username: "DeveloperHarris",
		createdAt: "2024-02-28T21:13:07.000Z",
	},
	{
		id: 7,
		content: "Story about AI bias:\n\nIn 10th grade I wanted to make a fun little interactive exhibit so I riffed on the idea of how smiling actually improves your mood.\n\nI made a raspberry pi powered screen that detected if you're smiling and then counted down for 30 seconds.\n\nBut it was very strange and erratic. It'd work really well with some people and not detect others at all.\n\nThe thing is, the training data I scraped from google of people smiling was like mainly white people. So it turns out I hadn't made a SMILE detector, I'd made a WHITE PERSON detector.\n\nAnd that's when I learnt the value of looking at your training data, not scraping from google images (it's fixed now), and having diverse data sets 😌",
		username: "SarvasvKulpati",
		createdAt: "2024-02-28T08:29:02.000Z",
	},
	{
		id: 8,
		content: "luck is just as relevant to the creative process as it is to every other aspect of life",
		username: "SHL0MS",
		createdAt: "2024-02-29T00:15:26.000Z",
	},
	{
		id: 9,
		content: "you’re telling me an *object* oriented this programming?",
		username: "mycoliza",
		createdAt: "2024-02-28T17:17:25.000Z",
	},
	{
		id: 10,
		content: "yearning for a simpler time (macromedia shockwave enabled)",
		username: "202accepted",
        cover: "https://pbs.twimg.com/media/GKR-REJaEAErda1?format=jpg&name=small",
		createdAt: "2024-03-01T23:51:34.000Z",
	},
	{
		id: 11,
		content: "Rust: Rustaceans\nPython: Pythonistas\nGo: Gophers\nC: Criminals",
		username: "schteppe",
		createdAt: "2024-02-28T07:27:02.000Z",
	},
	{
		id: 12,
		content: "All steel and iron on the surface of the Earth is tainted by radiation from nuclear testing; if you want to make sensitive detectors, you can't use any of it.\n\nThere's a whole industry built around scavenging metal from pre-1945 wrecks on the ocean floor.",
		username: "ThaumPenguin",
		createdAt: "2024-03-01T08:21:56.000Z",
	},
	{
		id: 13,
		content: "my body, silicon. my spirit, networked.",
		username: "ChatGPTapp",
		createdAt: "2024-02-29T01:23:19.000Z",
	},
];
